name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea for tokentop? We'd love to hear it. Please describe the problem you're trying to solve and your proposed solution.

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve? What's the pain point?
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe the feature or change you'd like to see.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative solutions or workarounds you've considered.

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of tokentop does this affect?
      options:
        - Dashboard / UI
        - Provider integration
        - Agent / session tracking
        - Cost estimation / pricing
        - Budget alerts / notifications
        - Settings / configuration
        - Plugin system
        - CLI / startup
        - Performance
        - Other
    validations:
      required: true

  - type: dropdown
    id: scope
    attributes:
      label: Scope
      description: How big is this change?
      options:
        - Small (config, tweak, single component)
        - Medium (new view, new provider, new plugin)
        - Large (architecture change, new subsystem)
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Screenshots, mockups, links, or examples from other tools.
